import { supabase } from "./lib/supabaseClient.js";
import { requireAdmin } from "./services/adminAuthService.js";
const rows=document.getElementById("rows"), status=document.getElementById("status"), pagination=document.getElementById("transaction-pagination");
const naira=new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN"});
const PAGE_SIZE=25; let page=1;
function renderPagination(totalPages){pagination.innerHTML="";if(totalPages<=1)return;const prev=document.createElement("button");prev.className="btn btn-secondary";prev.type="button";prev.textContent="Previous";prev.disabled=page<=1;prev.onclick=()=>{page-=1;load();};const label=document.createElement("span");label.className="admin-pagination__label";label.textContent=`Page ${page} of ${totalPages}`;const next=document.createElement("button");next.className="btn btn-secondary";next.type="button";next.textContent="Next";next.disabled=page>=totalPages;next.onclick=()=>{page+=1;load();};pagination.append(prev,label,next);}
async function load(){const from=(page-1)*PAGE_SIZE,to=from+PAGE_SIZE-1;const {data,error,count}=await supabase.from("payments").select("id,order_id,provider,provider_reference,amount,status,created_at",{count:"exact"}).order("created_at",{ascending:false}).range(from,to);if(error)throw error;rows.innerHTML=(data||[]).map(p=>`<tr><td>${p.id.slice(0,8)}</td><td>${p.order_id.slice(0,8)}</td><td>${p.provider||"—"}</td><td>${p.provider_reference||"—"}</td><td>${naira.format(Number(p.amount))}</td><td>${p.status}</td><td>${new Date(p.created_at).toLocaleString("en-NG")}</td></tr>`).join("")||'<tr><td colspan="7">No transactions yet.</td></tr>';renderPagination(Math.ceil((count||0)/PAGE_SIZE));}
async function init(){const access=await requireAdmin();if(!access){location.href="/admin/";return;}await load();}
init().catch(e=>{console.error(e);status.textContent="Could not load transactions.";status.hidden=false;});
